spring:
   data:
      mongodb:
         uri: mongodb+srv://pushpendra:EdL8YuatVzY7j5K@reachoutcluster-kalmu.mongodb.net/pushpendra_demo?retryWrites=true&w=majority

logging:
  level:
    ROOT: INFO
    com.micro: DEBUG
